platform :ios, '8.0'
target 'MapExample' do
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
